# @name Get all categories (paginated search)
GET {{host}}/categories?page=0&linesPerPage=5&direction=ASC&orderBy=name
Content-Type: application/json

###
# @name Get category by id
GET {{host}}/categories/4
Content-Type: application/json

###
# @name Create a new category
POST {{host}}/categories
Content-Type: application/json

{
  "name": "Garden"
}

###
# @name Update category by id
PUT {{host}}/categories/4
Content-Type: application/json

{
  "name": "Garden Updated"
}

###
# @name Delete category by id
DELETE {{host}}/categories/4
Content-Type: application/json

###