# @name Get all categories
GET {{host}}/categories
Content-Type: application/json

###
# @name Get category by id
GET {{host}}/categories/1
Content-Type: application/json

###
# @name Create a new category
POST {{host}}/categories
Content-Type: application/json

{
  "name": "Garden"
}

###
# @name Update category by id
PUT {{host}}/categories/4
Content-Type: application/json

{
  "name": "Garden Updated"
}