# @name Get all products (paginated search)
GET {{host}}/products?page=0&linesPerPage=5&direction=DESC&orderBy=price
Content-Type: application/json

###
# @name Get product by id
GET {{host}}/products/26
Content-Type: application/json

###
# @name Create a new product
POST {{host}}/products
Content-Type: application/json

{
  "name": "PS5",
  "description": "The new generation PS5 video game",
  "price": 600.0,
  "imgUrl": "",
  "date": "2020-07-20T10:00:00Z",
  "categories": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ]
}

###
# @name Update product by id
PUT {{host}}/products/26
Content-Type: application/json

{
  "name": "Updated product name",
  "description": "Updated product description",
  "price": 600.0,
  "imgUrl": "",
  "date": "2020-07-20T10:00:00Z",
  "categories": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ]
}

###
# @name Delete product by id
DELETE {{host}}/products/26
Content-Type: application/json

###